Description of ccvBowGetWordsClean
Home > caltech-image-search > ccvBowGetWordsClean.m
ccvBowGetWordsClean
PURPOSE
CCVBOWGETWORDSCLEAN cleans memory after computing word quantizations
SYNOPSIS
function ccvBowGetWordsClean(gws)
DESCRIPTION
 CCVBOWGETWORDSCLEAN cleans memory after computing word quantizations
 INPUTS
 ------
 gws     - the GetWords strcture to use, output from ccvBowGetWordsInit
 OUTPUTS
 -------
 See also ccvBowGetDict
CROSS-REFERENCE INFORMATION
This function calls:
ccvHkmClean CCVHKMCLEAN clears the memory for teh input hkm
ccvKdtClean CCVKDTCLEAN cleans the memory for the input kd-tree
ccvLshClean CCVLSHCLEAN cleans the input lsh
This function is called by:
DEMO DEMO a demo script to show typical usage
SUBFUNCTIONS
function cleanDict(dict, cluster)
SOURCE CODE
function ccvBowGetWordsClean(gws)
% CCVBOWGETWORDSCLEAN cleans memory after computing word quantizations
%
% INPUTS
% ------
% gws     - the GetWords strcture to use, output from ccvBowGetWordsInit
%
% OUTPUTS
% -------
%
% See also ccvBowGetDict
%
% Author: Mohamed Aly <malaa at vision d0t caltech d0t edu>
% Date: October 6, 2010
switch gws.type
  %flat dictionary
  case 'flat'
    %cluster
    cleanDict(gws.dict, gws.cluster);
  %per-class
  case 'per-class'
    for c=1:length(gws.dict), cleanDict(gws.dict{c}, gws.cluster); end;
end; %switch type
% -----------------------------------------------------------------------
% clusters the input data
function cleanDict(dict, cluster)
switch cluster
  case 'akmeans'
    ccvKdtClean(dict);
  case 'lsh'
    ccvLshClean(dict.lsh);
  case 'xkmeans'
    ccvLshClean(dict.lsh);
  case 'hkmeans'
    ccvHkmClean(dict);
end; %switch cluster