Description of ccvHkmClean
Home > caltech-image-search > ccvHkmClean.m
ccvHkmClean
PURPOSE
CCVHKMCLEAN clears the memory for teh input hkm
SYNOPSIS
function ccvHkmClean(hkm)
DESCRIPTION
 CCVHKMCLEAN clears the memory for teh input hkm
 INPUTS
 ------
 hkm       - the input hkm, which comes from ccvHkmCrate or ccvHkmImport
 OUTPUTS
 -------
 See also ccvHkmImport ccvHkmExport ccvHkmCreate ccvHkmKnn ccvHkmClean
   ccvHkmLeafIds
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
DEMO DEMO a demo script to show typical usage
ccvBowGetDict CCVBOWGETDICT computes the dictionary given the input data
ccvBowGetWordsClean CCVBOWGETWORDSCLEAN cleans memory after computing word quantizations
SOURCE CODE
function ccvHkmClean(hkm)
% CCVHKMCLEAN clears the memory for teh input hkm
%
% INPUTS
% ------
% hkm       - the input hkm, which comes from ccvHkmCrate or ccvHkmImport
%
% OUTPUTS
% -------
%
% See also ccvHkmImport ccvHkmExport ccvHkmCreate ccvHkmKnn ccvHkmClean
%   ccvHkmLeafIds
%
% Author: Mohamed Aly <malaa at vision d0t caltech d0t edu>
% Date: October 6, 2010
%call the mex file
mxHkmClean(hkm);