Description of ccvKdtClean
Home > caltech-image-search > ccvKdtClean.m
ccvKdtClean
PURPOSE
CCVKDTCLEAN cleans the memory for the input kd-tree
SYNOPSIS
function ccvKdtClean(kdt)
DESCRIPTION
 CCVKDTCLEAN cleans the memory for the input kd-tree
 INPUTS
 ------
 kdt       - the input kd-tree, output from CCVKDTCREATE
 OUTPUTS
 -------
 See also ccvKdtKnn ccvKdtCreate
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
DEMO DEMO a demo script to show typical usage
ccvAkmeansClean CCVAKMEANSCLEAN clears the kdtree within the akmeans structure
ccvAkmeansCreate CCVAKMEANS computes kmeans clustering on the input data using
ccvBowGetWordsClean CCVBOWGETWORDSCLEAN cleans memory after computing word quantizations
SOURCE CODE
function ccvKdtClean(kdt)
% CCVKDTCLEAN cleans the memory for the input kd-tree
%
% INPUTS
% ------
% kdt       - the input kd-tree, output from CCVKDTCREATE
%
% OUTPUTS
% -------
%
% See also ccvKdtKnn ccvKdtCreate
%
% Author: Mohamed Aly <malaa at vision d0t caltech d0t edu>
% Date: October 6, 2010
%call the mex file
mxKdtClean(kdt);