Description of ccvLshClean
Home > caltech-image-search > ccvLshClean.m
ccvLshClean
PURPOSE
CCVLSHCLEAN cleans the input lsh
SYNOPSIS
function ccvLshClean(lsh)
DESCRIPTION
 CCVLSHCLEAN cleans the input lsh
 INPUTS
 ------
 lsh       - the input lsh
 OUTPUTS
 -------
 See also ccvLshCreate ccvLshInsert ccvLshLoad ccvLshSave ccvLshSearch
 ccvLshBucketId ccvLshFuncVal ccvLshStats ccvLshBucketPoints ccvLshKnn
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
DEMO DEMO a demo script to show typical usage
ccvBowGetDict CCVBOWGETDICT computes the dictionary given the input data
ccvBowGetWordsClean CCVBOWGETWORDSCLEAN cleans memory after computing word quantizations
SOURCE CODE
function ccvLshClean(lsh)
% CCVLSHCLEAN cleans the input lsh
%
% INPUTS
% ------
% lsh       - the input lsh
%
% OUTPUTS
% -------
%
% See also ccvLshCreate ccvLshInsert ccvLshLoad ccvLshSave ccvLshSearch
% ccvLshBucketId ccvLshFuncVal ccvLshStats ccvLshBucketPoints ccvLshKnn
% Author: Mohamed Aly <malaa at vision d0t caltech d0t edu>
% Date: October 6, 2010
%call the mex file
mxLshClean(lsh);